# -*- coding: utf-8 -*-
"""Homework_for_seminar_09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1msRKflH44bNSf3wyfH1zz9U-TEEBHnVT
"""

import pandas as pd
df = pd.read_csv('sample_data/california_housing_train.csv')

#Задача 40: Определить среднюю стоимость дома, где кол-во людей от 0 до 500 (population)
df[df['population'] < 500, ['housing_medium_value']]

#Задача 42: Узнать какая максимальная households в зоне минимального значения population
df1 = df.loc[df.population < df.population.quantile(.25)]
df1.households.max()